# ftp://ftp.irisa.fr/local/texmex/corpus/bigann_base.bvecs.gz
# ftp://ftp.irisa.fr/local/texmex/corpus/bigann_learn.bvecs.gz
# ftp://ftp.irisa.fr/local/texmex/corpus/bigann_query.bvecs.gz
# ftp://ftp.irisa.fr/local/texmex/corpus/bigann_gnd.tar.gz